<?php
/**
 * @file
 * Code for the luggage_core feature.
 */

include_once 'luggage_core.features.inc';

/**
 * Implements hook_update_projects_alter().
 */
function luggage_core_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['luggage_core']);
}

/**
 * Implements hook_init()
 */
function luggage_core_init() {
  // init luggage versions
  foreach (glob(DRUPAL_ROOT . "/*_VERSION.php") as $filename) {
    require_once($filename);
  }
}

/**
 * Implements hook_requirements()
 * @param $phase
 * @return array
 */
function luggage_core_requirements($phase) {
  if($phase == 'runtime') {
    $requirements = array();
    foreach (glob(DRUPAL_ROOT . "/*_VERSION.php") as $filename) {
      $var = trim(substr(basename($filename), 0, -4));
      $requirements[$var] = array(
        'title' => $var,
        'value' => constant($var),
      );
    }
    return $requirements;
  }
}
